on:
  push:
    branches:
      - master

name: Build and deploy

jobs:

  # prepare:
  #   name: Prepare Package
  #   runs-on: ubuntu-latest
  #   outputs:
  #     build_version:
  #       description: The version to set the plugin and filename to
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1

  #   - name: Generate Build Number
  #     id: gen-build-num
  #     env:
  #       REF: ${{ github.ref }}
  #       BUILD_NUMBER: ${{ github.run_number }}
  #     run: |
  #       VERSION=$(cat wp-hexly-utils.php | grep "Version:" -m1 | awk '{print $2}' | sed "s/__build-number__/foobar/")
  #       echo "::set-output name=build_version::$VERSION"


  build:
    name: Build
    # needs: prepare
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Generate Build Number
      id: gen-build-num
      env:
        REF: ${{ github.ref }}
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        VERSION=$(cat wp-hexly-utils.php | grep "Version:" -m1 | awk '{print $2}' | sed "s/__build-number__/foobar/")
        echo "::set-output name=build_version::$VERSION"

    - name: Composer install
      uses: docker://composer:1.9.1
      with:
        args: install

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUILD_VERSION: ${{ steps.gen-build-num.outputs.build_version }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        # echo '@hexly:registry=https://npm.pkg.github.com/' >> .npmrc
        # echo $GITHUB_PACKAGE_AUTH >> .npmrc

        sed -i -e "s/Version: .*__build-number__/${BUILD_VERSION}/" ./wp-hexly-utils.php
        cat ./wp-hexly-utils.php
        aws s3 ls
        ls -alh
        echo "Built ${BUILD_VERSION}"

    # - uses: montudor/action-zip@v0.1.0
    #   with:
    #     args: zip -qq -r ./wp-hexly-utils.zip ./dir