on:
  push:
    branches:
      - master

name: Build and deploy

env:
  PROJECT: wp-hexly-utils
  PLUGIN_FILE: wp-hexly-utils.php
  S3_DESTINATION_DIR: s3://plugins.hexly.cloud/wp/plugins

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Generate Build Number
      id: gen-build-num
      env:
        REF: ${{ github.sha }}
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        CMD="cat $PLUGIN_FILE | grep 'Version:' -m1 | awk '{print \$2}' | sed -e 's/__build-number__/$BUILD_NUMBER.${REF::8}/'"
        echo "Running $CMD"
        VERSION=$(bash -c "$CMD")
        echo "::set-output name=build_version::$VERSION"

    - name: Composer install
      uses: docker://composer:1.9.1
      with:
        args: install

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUILD_VERSION: ${{ steps.gen-build-num.outputs.build_version }}
      run: |
        sed -i -e "s/Version: .*__build-number__/Version: ${BUILD_VERSION}/" ./$PLUGIN_FILE
        BASE_DIR=$(pwd)
        ZIP_FILE="$PROJECT-$BUILD_VERSION.zip"
        ZIP="$BASE_DIR/$PLUGIN/$ZIP_FILE"
        bash build/zip.sh "$ZIP" "$BASE_DIR" "$PLUGIN" "$BUILD_VERSION"
        aws s3 cp "$ZIP" "s3://plugins.hexly.cloud/wp/plugins/$PROJECT/$ZIP_FILE"

        sed -i -e "s/{{ \.ZIP_FILE }}/$ZIP_FILE/g" build/update-meta.json
        sed -i -e "s/{{ \.PROJECT }}/$PROJECT/g" build/update-meta.json
        cat build/update-meta.json
        aws s3 cp build/update-meta.json "s3://plugins.hexly.cloud/wp/plugins/$PROJECT/update-meta.json"